
name: Test Secrets on Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: self-hosted

    steps:
      - name: Print masked secret
        shell: powershell
        run: |
          Write-Output "The secret token is: $env:MY_SECRET_TOKEN"

        env:
          MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

      - name: Use secret in logic
        shell: powershell
        run: |
          if ($env:MY_SECRET_TOKEN -eq "this_is_my_secret") {
            Write-Output "✅ Secret value matched!"
          } else {
            Write-Output "❌ Secret mismatch or not set"
          }
        env:
          MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

