name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [18.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: react/package-lock.json

    - name: installing dependency
      run: cd react && npm i
    
    - name: runn build command
      run: cd react && npm run build


  run_tests:
    needs: build
    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [18.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: react/package-lock.json

    - name: installing dependency
      run: cd react && npm i
    
    - name: run tests cases
      run: cd react && npm run test


